export const ADD_FILM = "ADD_FILM";
export const ADD_FILMS = "ADD_FILMS";
export const DELETE_FILM = "DELETE_FILM";
export const SEARCH_FILMS_BY_TITLE = "SEARCH_FILMS_BY_TITLE";
export const SEARCH_FILMS_BY_STARS = "SEARCH_FILMS_BY_STARS";
